import { useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react';
import { ArrowLeft, Home, Lock, Play, Pause, ChevronDown, Info, Check, RotateCcw, Volume2, Crosshair, Shield, Zap } from 'lucide-react';
import { nav, skills, teams, players, matchResults, shotTypes, type Screen } from './data';

const Btn=({children,onClick,kind='primary',disabled=false,className=''}:{children:any,onClick?:()=>void,kind?:string,disabled?:boolean,className?:string})=><button disabled={disabled} onClick={onClick} className={`btn ${kind} ${className}`}>{children}</button>;
const Card=({children,className='',title}:{children:any,className?:string,title?:string})=><section className={`card ${className}`}>{title&&<h3>{title}</h3>}{children}</section>;
const Select=({label,value,options,onChange}:{label:string,value:string,options:string[],onChange?:(v:string)=>void})=><label className="field"><span>{label}</span><div className="select-wrap"><select value={value} onChange={e=>onChange?.(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select><ChevronDown size={15}/></div></label>;
const Slider=({label,value=60,onChange}:{label:string,value?:number,onChange?:(v:number)=>void})=><label className="field slider"><span>{label}<b>{value}%</b></span><input type="range" value={value} onChange={e=>onChange?.(+e.target.value)}/></label>;
const Progress=({value,label}:{value:number,label?:string})=><div className="progress-wrap">{label&&<span>{label}</span>}<div className="progress"><i style={{width:`${value}%`}}/></div></div>;
const Tabs=({items,active,set}:{items:string[],active:string,set:(x:string)=>void})=><div className="tabs">{items.map(x=><button className={active===x?'active':''} onClick={()=>set(x)} key={x}>{x}</button>)}</div>;

function TopBar({screen,setScreen}:{screen:Screen,setScreen:(s:Screen)=>void}){return <header className="topbar"><div className="top-left">{screen!=='home'&&<><button aria-label="Back" onClick={()=>setScreen('home')}><ArrowLeft/></button><button aria-label="Home" onClick={()=>setScreen('home')}><Home/></button></>}<div className="brand"><span>⚽</span><b>KICK THAT BALL!</b></div></div><div className="status"><span className="level">LVL 12</span><span>🪙 <b>2,480</b></span><span className="avatar">NC</span></div></header>}
function Header({eyebrow,title,sub}:{eyebrow:string,title:string,sub:string}){return <div className="page-head"><div><small>{eyebrow}</small><h1>{title}</h1><p>{sub}</p></div><div className="rank">BRONZE III <b>1,840 XP</b></div></div>}
function FieldPreview({defenders=3,angle=20,keeper=true}:{defenders?:number,angle?:number,keeper?:boolean}){return <div className="field-preview"><div className="goal">{keeper&&<i className="keeper">GK</i>}</div><div className="wall">{Array.from({length:defenders}).map((_,i)=><i key={i} style={{left:`${38+i*8}%`}}>●</i>)}</div><div className="shot-line" style={{transform:`rotate(${angle-20}deg)`}}/><div className="ball">⚽</div><span className="distance">24m</span></div>}

function HomeScreen({go}:{go:(s:Screen)=>void}){return <><div className="hero"><div><small>WELCOME BACK, NOVA</small><h1>Your pitch.<br/><em>Your moment.</em></h1><p>One more win to reach the Bronze Final.</p><Btn onClick={()=>go('play')}><Play size={18} fill="currentColor"/> PLAY NOW</Btn></div><div className="player-art"><span>11</span><b>NOVA</b></div></div><div className="home-grid"><Card className="daily"><small>DAILY CHALLENGE · 08:42:16</small><h3>Curve Master</h3><p>Score 3 curved shots in any mode</p><Progress value={66} label="2 / 3 goals"/><b className="reward">+250 🪙</b></Card><Card className="featured"><small>FEATURED MODE</small><h3>Neon Nights</h3><p>Trick-shot showdown · 2x XP</p><Btn onClick={()=>go('multiplayer')} kind="secondary">JOIN EVENT</Btn></Card></div><div className="menu-grid">{nav.map(x=><button key={x.id} onClick={()=>go(x.id)}><i>{x.icon}</i><span><b>{x.label}</b><small>{x.sub}</small></span><strong>›</strong></button>)}</div></>}

function PlayScreen({go}:{go:(s:Screen)=>void}){const [mode,setMode]=useState('Quick Match');const [diff,setDiff]=useState('Normal');return <><Header eyebrow="MATCH CENTER" title="Choose your game" sub="Set the stage, then take the pitch."/><div className="mode-grid">{['Quick Match','Play Against AI','Real Match','Ranked Match','Tournament','Goalkeeper Mode'].map((x,i)=><button className={mode===x?'selected':''} onClick={()=>setMode(x)} key={x}><i>{['⚡','◉','🏟','♛','🏆','🧤'][i]}</i><b>{x}</b><small>{i===3?'Earn rank points':'Customize and play'}</small>{mode===x&&<Check/>}</button>)}</div><Card title="MATCH SETUP"><div className="form-grid"><Select label="Match length" value="8 minutes" options={['4 minutes','8 minutes','12 minutes']}/><Select label="AI difficulty" value={diff} onChange={setDiff} options={['Beginner','Easy','Normal','Hard','Expert','Legendary']}/><Select label="Your team" value={teams[0]} options={teams}/><Select label="Stadium" value="Aurora Bowl" options={['Aurora Bowl','Metro Park','Tide Arena']}/><Select label="Weather" value="Clear" options={['Clear','Rain','Light Snow']}/><Select label="Time of day" value="Night" options={['Day','Sunset','Night']}/></div></Card><div className="actionbar"><span><b>{mode}</b> · {diff} difficulty</span><Btn onClick={()=>go(mode==='Goalkeeper Mode'?'goalkeeper':'match')}>START MATCH <Play size={17}/></Btn></div></>}

function PracticeScreen(){const [tab,setTab]=useState('Free Kick');const [defs,setDefs]=useState(3);const [angle,setAngle]=useState(20);return <><Header eyebrow="TRAINING GROUND" title="Build the perfect drill" sub="Adjust the scenario and see it update live."/><Tabs items={['Free Kick','Game Situation']} active={tab} set={setTab}/><div className="split"><Card className="preview-card"><div className="card-title"><span>LIVE PREVIEW</span><b>{tab==='Free Kick'?'CURVED SHOT · 24M':'ATTACKING · 01:30'}</b></div><FieldPreview defenders={defs} angle={angle}/><div className="preview-stats"><span>ANGLE <b>{angle}°</b></span><span>DEFENDERS <b>{defs}</b></span><span>KEEPER <b>HARD</b></span></div></Card><Card className="config" title="DRILL CONFIGURATION">{tab==='Free Kick'?<><Slider label="Shooting angle" value={angle} onChange={setAngle}/><Slider label="Ball position" value={42}/><Slider label="Distance from goal" value={55}/><Select label="Number of defenders" value={String(defs)} onChange={v=>setDefs(+v)} options={['0','1','2','3','4','5']}/><Select label="Defender placement" value="Compact wall" options={['Compact wall','Split wall','Random']}/><Select label="Defender height" value="Mixed" options={['Short','Mixed','Tall']}/><Select label="Goalkeeper level" value="Hard" options={['Beginner','Normal','Hard','Legendary']}/><Select label="Wall position" value="Center" options={['Left','Center','Right']}/><Select label="Shot type" value="Curved Shot" options={['Normal Shot','Power Shot','Curved Shot','Chip Shot','Low Shot','Pass Into Goal']}/></>:<><Select label="Scenario" value="Last-minute goal" options={['One-on-one with goalkeeper','Two attackers versus one defender','Counterattack','Last-minute goal','Cross into the box','Corner kick','Defend a lead']}/><Select label="Attacking or defending" value="Attacking" options={['Attacking','Defending']}/><Select label="Starting position" value="Right channel" options={['Center','Left channel','Right channel']}/><Select label="Current score" value="1 – 1" options={['0 – 0','0 – 1','1 – 1','2 – 1']}/><Slider label="Time remaining" value={25}/><Slider label="Defender speed" value={70}/><Slider label="Defender skill" value={65}/><Slider label="Teammate skill" value={72}/><Select label="Defenders / teammates" value="2 / 2" options={['1 / 1','2 / 1','2 / 2','3 / 2']}/></>}<Btn className="wide">START DRILL <Play size={16}/></Btn></Card></div></>}

function Multiplayer(){const [round,setRound]=useState(2);const angles=[-15,32,8,24,40];return <><Header eyebrow="LIVE CHALLENGE" title="Trick-shot showdown" sub="Same spot. Same conditions. Make it spectacular."/><div className="round-strip"><span>ROUND <b>{round}</b> / 5</span><span>ANGLE <b>{angles[round-1]}°</b></span><span>DISTANCE <b>{18+round*2}m</b></span><span>WIND <b>{round+1} km/h →</b></span><span className="timer">SHOT TIMER <b>00:{14-round}</b></span></div><div className="split"><Card className="preview-card"><FieldPreview defenders={1} angle={angles[round-1]}/><div className="player-order"><small>PLAYER ORDER</small>{['NOVA · YOU','VEX','MIRA','JAX'].map((x,i)=><span className={i===1?'active':''} key={x}><b>{i+1}</b>{x}</span>)}</div></Card><Card title="SCOREBOARD"><div className="scoreboard">{[['MIRA',1840],['NOVA',1725],['VEX',1610],['JAX',1420]].map((x,i)=><div key={String(x[0])}><b>{i+1}</b><span>{x[0]}{x[0]==='NOVA'&&<small> YOU</small>}</span><strong>{x[1]}</strong></div>)}</div><h4>PREVIOUS SHOT</h4><div className="score-cats">{['Accuracy 92','Power 78','Curve 88','Style 95','Difficulty 84','Placement 90'].map(x=><span key={x}>{x}</span>)}</div><div className="shot-total"><small>SHOT SCORE</small><b>527</b></div><Btn className="wide" onClick={()=>setRound(round===5?1:round+1)}>NEXT ROUND <RotateCcw size={16}/></Btn></Card></div></>}

function Match({go}:{go:(s:Screen)=>void}){
  const [shoot,setShoot]=useState(false);const [pass,setPass]=useState(false);const [paused,setPaused]=useState(false);
  const [score,setScore]=useState({sol:0,emb:0});const [goalMessage,setGoalMessage]=useState('');
  const [stick,setStick]=useState({x:0,y:0});const [player,setPlayer]=useState({x:50,y:55});const joystickRef=useRef<HTMLDivElement>(null);const fieldRef=useRef<HTMLDivElement>(null);
  const [ball,setBall]=useState({x:53,y:59});const ballRef=useRef(ball);const velocityRef=useRef({x:0,y:0});const possessionRef=useRef(false);
  useEffect(()=>{ballRef.current=ball},[ball]);
  useEffect(()=>{if(paused)return;let frame=0;let previous=performance.now();const tick=(now:number)=>{const dt=Math.min(2,(now-previous)/16.67);previous=now;const velocity=velocityRef.current;if(Math.hypot(velocity.x,velocity.y)>.015){let x=ballRef.current.x+velocity.x*dt;let y=ballRef.current.y+velocity.y*dt;const topGoal=y<=10&&x>=39&&x<=61;const bottomGoal=y>=88&&x>=39&&x<=61;if(topGoal||bottomGoal){const scoringTeam=topGoal?'SOL':'EMB';setScore(s=>topGoal?{...s,sol:s.sol+1}:{...s,emb:s.emb+1});setGoalMessage(`${scoringTeam} GOAL!`);window.setTimeout(()=>setGoalMessage(''),1100);possessionRef.current=false;velocityRef.current={x:0,y:0};const resetBall={x:50,y:58};ballRef.current=resetBall;setBall(resetBall);setPlayer({x:50,y:55})}else{if(x<16||x>84){x=Math.max(16,Math.min(84,x));velocity.x*=-.68}if(y<8||y>90){y=Math.max(8,Math.min(90,y));velocity.y*=-.68}velocity.x*=Math.pow(.965,dt);velocity.y*=Math.pow(.965,dt);const next={x,y};ballRef.current=next;setBall(next)}}else velocityRef.current={x:0,y:0};frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[paused]);
  function kickBall(power=1){if(paused)return;const current=ballRef.current;const distance=Math.hypot(current.x-player.x,current.y-player.y);if(!possessionRef.current&&distance>12)return;let dx=current.x-player.x;let dy=current.y-player.y;if(Math.hypot(dx,dy)<1){dx=0;dy=-1}const length=Math.hypot(dx,dy);possessionRef.current=false;velocityRef.current={x:dx/length*1.15*power,y:dy/length*1.15*power};setShoot(true);window.setTimeout(()=>setShoot(false),180)}
  function moveJoystick(e:ReactPointerEvent<HTMLDivElement>){if(paused||!joystickRef.current)return;const rect=joystickRef.current.getBoundingClientRect();const radius=rect.width/2;const knobRadius=(joystickRef.current.querySelector('i')?.getBoundingClientRect().width??radius*.9)/2;const max=Math.max(1,radius-knobRadius-2);const dx=e.clientX-(rect.left+radius);const dy=e.clientY-(rect.top+radius);const distance=Math.hypot(dx,dy)||1;const scale=Math.min(1,max/distance);const x=dx*scale;const y=dy*scale;setStick({x,y});setPlayer(p=>{const field=fieldRef.current?.getBoundingClientRect();const markerRadius=19;const radiusX=field?markerRadius/field.width*100:3;const radiusY=field?markerRadius/field.height*100:3;const minX=15+radiusX;const maxX=85-radiusX;const minY=10+radiusY;const maxY=90-radiusY;const next={x:Math.max(minX,Math.min(maxX,p.x+x/max*1.8)),y:Math.max(minY,Math.min(maxY,p.y+y/max*1.8))};const currentBall=ballRef.current;const closeEnough=Math.hypot(currentBall.x-next.x,currentBall.y-next.y)<10;const ballIsLoose=Math.hypot(velocityRef.current.x,velocityRef.current.y)<.08;if(ballIsLoose&&(possessionRef.current||closeEnough)){possessionRef.current=true;velocityRef.current={x:0,y:0};const nextBall={x:Math.max(16,Math.min(84,next.x+x/max*5.2)),y:Math.max(8,Math.min(90,next.y+y/max*5.2))};ballRef.current=nextBall;setBall(nextBall)}return next})}
  function startJoystick(e:ReactPointerEvent<HTMLDivElement>){e.currentTarget.setPointerCapture(e.pointerId);moveJoystick(e)}
  function stopJoystick(e:ReactPointerEvent<HTMLDivElement>){if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);setStick({x:0,y:0})}
  return <div className="match-screen"><div className="match-top"><button onClick={()=>setPaused(!paused)}>{paused?<Play/>:<Pause/>}</button><div><span>SOL <b>{score.sol}</b></span><i>Q3 · 04:18</i><span><b>{score.emb}</b> EMB</span></div><button onClick={()=>go('coach')}>COACH · 3</button></div><div ref={fieldRef} className="match-field"><div className="mini-map">{[1,2,3,4,5,6,7,8].map(i=><i key={i}/>)}</div><div className="pitch-goal top-goal"><span>SOL GOAL</span></div><div className="pitch-goal bottom-goal"><span>EMB GOAL</span></div>{goalMessage&&<div className="goal-message">{goalMessage}</div>}<div className="selected-player" style={{left:`${player.x}%`,top:`${player.y}%`}}><span>NOVA 11</span><i/></div><button className="game-ball" aria-label="Kick the ball" title="Kick the ball" style={{left:`${ball.x}%`,top:`${ball.y}%`}} onPointerDown={e=>{e.preventDefault();kickBall(1.15)}}>⚽</button>{pass&&<><span className="target t1">A</span><span className="target t2">B</span><span className="target t3">C</span></>}{shoot&&<div className="goal-zones"><i/><i/><i/><i/></div>}<div className="stamina"><b>STAMINA</b><Progress value={74}/></div><div ref={joystickRef} className="joystick" role="button" aria-label="Movement joystick" onPointerDown={startJoystick} onPointerMove={e=>e.currentTarget.hasPointerCapture(e.pointerId)&&moveJoystick(e)} onPointerUp={stopJoystick} onPointerCancel={stopJoystick}><i style={{transform:`translate(${stick.x}px,${stick.y}px)`}}/></div><div className="controls"><button onClick={()=>setPass(!pass)} className={pass?'on':''}>PASS</button><button onClick={()=>kickBall(1.7)} className={`shoot ${shoot?'on':''}`}>SHOOT{shoot&&<i/>}</button><button>SPRINT</button><button>SKILL</button><button>SWITCH</button><button>TACKLE</button></div></div>{paused&&<div className="overlay"><Card><h2>Match paused</h2><p>Take a breath. The pitch will wait.</p><Btn onClick={()=>setPaused(false)}>RESUME</Btn><Btn kind="ghost" onClick={()=>go('home')}>EXIT TO HOME</Btn></Card></div>}</div>
}

function Skills(){const [equipped,setEquipped]=useState<string[]>(['Maradona Turn','Scissors','Elastico']);const [selected,setSelected]=useState('Maradona Turn');const [dir,setDir]=useState('Move left');const skill=skills.find(x=>x[0]===selected)!;function toggle(n:string,status:string){if(status==='locked')return;setEquipped(e=>e.includes(n)?e.filter(x=>x!==n):e.length<5?[...e,n]:e)}return <><Header eyebrow="PLAYER LOADOUT" title="Skill inventory" sub="Equip up to five moves for your next match."/><Card className="slots"><div className="card-title"><span>EQUIPPED SKILLS</span><b>{equipped.length} / 5 SLOTS</b></div><div className="skill-slots">{Array.from({length:5}).map((_,i)=><button key={i} onClick={()=>equipped[i]&&setSelected(equipped[i])} className={equipped[i]===selected?'active':''}><i>{equipped[i]?'✦':i+1}</i><span>{equipped[i]||'Empty slot'}</span>{equipped[i]&&<small onClick={e=>{e.stopPropagation();toggle(equipped[i],'unlocked')}}>×</small>}</button>)}</div></Card><div className="split skills-layout"><div className="skill-list">{skills.map(s=><button className={`${selected===s[0]?'selected':''} ${s[3]}`} onClick={()=>setSelected(s[0])} key={s[0]}><i>{s[3]==='locked'?<Lock/>:'✦'}</i><span><b>{s[0]}</b><small className={s[1].toLowerCase()}>{s[1]}</small></span>{equipped.includes(s[0])&&<Check/>}</button>)}</div><Card className="skill-detail"><div className="skill-demo"><span>PREVIEW</span><i>⚽</i></div><small>{skill[1]} SKILL</small><h2>{skill[0]}</h2><p>{skill[2]}. Time it at the edge of a challenge to keep momentum.</p>{selected==='Scissors'&&<Tabs items={['Move left','Move right']} active={dir} set={setDir}/>}<Btn kind="secondary"><Play size={16}/> PREVIEW MOVE</Btn><Btn disabled={skill[3]==='locked'||(!equipped.includes(selected)&&equipped.length>=5)} onClick={()=>toggle(selected,skill[3])}>{equipped.includes(selected)?'UNEQUIP':skill[3]==='locked'?'LOCKED':'EQUIP SKILL'}</Btn>{equipped.length>=5&&!equipped.includes(selected)&&<p className="warning">All five slots are full. Unequip a skill first.</p>}</Card></div></>}

function Shooting(){const [context,setContext]=useState('Open play');const [tip,setTip]=useState('');return <><Header eyebrow="SHOT LOCKER" title="Choose your finish" sub="Availability changes with the moment on the pitch."/><div className="context"><span>TEST CONTEXT</span>{['Open play','Free kick','Ball airborne','Ball behind'].map(x=><button className={context===x?'active':''} onClick={()=>setContext(x)} key={x}>{x}</button>)}</div><div className="shot-grid">{shotTypes.map((s,i)=>{const disabled=(s[2]==='free kick only'&&context!=='Free kick')||(s[2]==='airborne'&&context!=='Ball airborne')||(s[2]==='behind player'&&context!=='Ball behind');return <button key={s[0]} className={disabled?'disabled':''} onMouseEnter={()=>disabled&&setTip(s[0])} onMouseLeave={()=>setTip('')}><i>{['◎','⚡','◔','→','⌒','↟','⟳'][i]}</i><b>{s[0]}</b><small>{s[1]}</small>{disabled&&<Lock/>}{tip===s[0]&&<span className="tooltip"><Info size={14}/>{s[0]==='Bicycle Kick'?'Ball must be airborne and behind your player.':s[0]==='Volley'?'Wait until the ball is airborne.':'Primarily available during free kicks.'}</span>}</button>})}</div><Card className="tip-card"><Info/><div><b>CONTEXT-SENSITIVE SHOTS</b><p>Unavailable moves stay visible so you can learn when they activate. Switch the test context above to preview each state.</p></div></Card></>}

function Goalkeeper(){const [state,setState]=useState('SET');const [practice,setPractice]=useState(true);return <div className="keeper-screen"><div className="keeper-top"><button onClick={()=>history.back()}><ArrowLeft/></button><div><span>REACTION</span><Progress value={68}/></div><b>{state}</b><button onClick={()=>setPractice(!practice)}>TRAJECTORY {practice?'ON':'OFF'}</button></div><div className="keeper-view"><div className="incoming">INCOMING <b>↙</b><span>0.42s</span></div>{practice&&<div className="trajectory"/>}<div className="position-guide"><i/><span>POSITION: GOOD</span></div><div className="keeper-body">🧤</div><div className="decision"><button onClick={()=>setState('CATCHING')}>CATCH</button><button onClick={()=>setState('DEFLECTING')}>DEFLECT</button></div><div className="keeper-controls">{['Dive Left','Dive Right','Catch','Jump','Sprint Out','Knees Left','Knees Right','Smother','Hard Kick','Punt','Bounce + Kick'].map(x=><button onClick={()=>setState(x.toUpperCase())} key={x}>{x}</button>)}</div><div className="keeper-notes"><span>LEG SAVE <b>POSSIBLE</b></span><span>RECOVERY <b>{state==='SET'?'READY':'0.8s'}</b></span></div></div></div>}

function Team(){const [tab,setTab]=useState('Identity');const [team,setTeam]=useState(teams[0]);return <><Header eyebrow="CLUBHOUSE" title="Make it yours" sub="Build a fictional club with a style all its own."/><Tabs items={['Identity','Squad','Matchday']} active={tab} set={setTab}/><div className="split"><Card className="team-card"><div className="crest">☀</div><h2>{team}</h2><span>AURORA PREMIER LEAGUE</span><div className="jersey">11</div><b>NOVA CRUZ · CAPTAIN</b></Card><Card title={`${tab.toUpperCase()} OPTIONS`}><div className="form-grid">{tab==='Identity'?<><Select label="Country" value="Auroria" options={['Auroria','Northwind Isles','Ember Republic']}/><Select label="League" value="Aurora Premier" options={['Aurora Premier','Coastal Championship']}/><Select label="Team" value={team} onChange={setTeam} options={teams}/><Select label="Team card decoration" value="Solar Flare" options={['Solar Flare','Midnight Lines','Clean White']}/></>:tab==='Squad'?<><Select label="Coach" value="Ari Santos" options={['Ari Santos','Robin Vale','Casey North']}/><Select label="Featured player" value="Nova Cruz" options={players.map(x=>x.name)}/><Select label="Formation" value="4-3-3" options={['4-3-3','4-4-2','3-5-2']}/><Select label="Captain" value="Nova Cruz" options={players.map(x=>x.name)}/></>:<><Select label="Referee" value="Morgan Swift" options={['Morgan Swift','Jules Reed']}/><Select label="Jersey" value="Sunburst Home" options={['Sunburst Home','Night Away']}/><Select label="Ball" value="Pulse Pro" options={['Pulse Pro','Orbit Match']}/><Select label="Stadium" value="Aurora Bowl" options={['Aurora Bowl','Metro Park']}/></>}</div><Btn className="wide">SAVE CHANGES <Check size={16}/></Btn></Card></div></>}

function Coach(){const [timeouts,setTimeouts]=useState(3);const [attack,setAttack]=useState(62);return <><Header eyebrow="Q3 BREAK · 04:18" title="Coach's board" sub="Adjust the plan before play resumes."/><div className="breaks">{['First quarter','Halftime','Third quarter','End of game'].map((x,i)=><span className={i<3?'done':''} key={x}>{i<3?<Check/>:i+1}<b>{x}</b></span>)}</div><div className="split"><Card title="TACTICAL PLAN"><Select label="Formation" value="4-3-3 Attack" options={['4-3-3 Attack','4-4-2 Balanced','5-3-2 Defend']}/><Slider label="Attacking level" value={attack} onChange={setAttack}/><Slider label="Defensive level" value={55}/><Slider label="Team pressure" value={72}/><div className="timeouts"><b>COACH TIMEOUTS</b><div>{[0,1,2].map(i=><i className={i<timeouts?'left':''} key={i}>T</i>)}</div><Btn disabled={!timeouts} onClick={()=>setTimeouts(x=>x-1)}>USE TIMEOUT</Btn></div></Card><Card title="SQUAD & STAMINA"><div className="squad">{players.map(p=><div key={p.name}><span className="avatar">{p.pos}</span><span><b>{p.name}</b><small>{p.pos} · OVR {p.ovr}</small></span><Progress value={55+Math.random()*35}/><button>SUB</button></div>)}</div><Btn className="wide">CONFIRM & RESUME <Play size={16}/></Btn></Card></div></>}

function Progression(){return <><Header eyebrow="PLAYER JOURNEY" title="Bronze III" sub="One strong match can take you to the promotion final."/><Card className="xp-card"><div><small>CURRENT XP</small><b>1,840 <i>/ 2,000</i></b></div><Progress value={92}/><span>160 XP TO SILVER I</span></Card><div className="rank-road">{['Bronze I','Bronze II','Bronze III','Silver I','Silver II','Silver III','Gold I','Gold II','Gold III'].map((x,i)=><div className={i<2?'done':i===2?'current':'locked'} key={x}><i>{i<3?'◆':<Lock/>}</i><b>{x}</b></div>)}</div><div className="stats-grid">{[['WINS','28'],['GOALS','64'],['ASSISTS','31'],['SAVES','12'],['RATING','8.4']].map(x=><Card key={x[0]}><small>{x[0]}</small><b>{x[1]}</b></Card>)}</div><div className="split"><Card title="RECENT MATCHES"><div className="results">{matchResults.map(x=><div key={x[0]+x[1]}><i className={x[3]==='W'?'win':''}>{x[3]}</i><span>{x[0]} <b>{x[1]}</b> {x[2]}</span></div>)}</div></Card><Card title="NEXT UNLOCKS"><div className="unlocks"><span>✦<b>Rainbow Flick</b><small>Silver I</small></span><span>👕<b>Solar Away Kit</b><small>1,950 XP</small></span><span>⚽<b>Orbit Ball</b><small>Silver II</small></span></div></Card></div></>}

function Settings(){const [left,setLeft]=useState(false);const [quality,setQuality]=useState('High');return <><Header eyebrow="PREFERENCES" title="Settings" sub="Tune the game to feel right for you."/><div className="settings-grid"><Card title="AUDIO"><Slider label="Music volume" value={72}/><Slider label="Sound effects volume" value={88}/><Slider label="Commentary volume" value={64}/></Card><Card title="CONTROLS"><Slider label="Camera sensitivity" value={55}/><Slider label="Button size" value={70}/><Slider label="Button transparency" value={18}/>{[['Left-handed controls',left,setLeft],['Vibration',true,()=>{}],['Automatic player switching',true,()=>{}],['Aim assistance',true,()=>{}]].map((x:any)=><label className="toggle" key={x[0]}><span>{x[0]}</span><input type="checkbox" checked={x[1]} onChange={e=>x[2](e.target.checked)}/><i/></label>)}</Card><Card title="VIDEO & ACCESSIBILITY"><Select label="Performance quality" value={quality} onChange={setQuality} options={['Low','Medium','High','Ultra']}/><Select label="Colorblind accessibility" value="Off" options={['Off','Deuteranopia','Protanopia','Tritanopia']}/><label className="toggle"><span>Tutorial prompts</span><input type="checkbox" defaultChecked/><i/></label><div className="quality"><Volume2/><span><b>{quality} quality</b><small>Balanced for this device</small></span></div></Card></div><div className="actionbar"><span>Changes apply instantly</span><Btn>CONFIRM SETTINGS <Check size={16}/></Btn></div></>}

export default function App(){const [screen,setScreen]=useState<Screen>('home');let body:any;switch(screen){case'home':body=<HomeScreen go={setScreen}/>;break;case'play':body=<PlayScreen go={setScreen}/>;break;case'practice':body=<PracticeScreen/>;break;case'multiplayer':body=<Multiplayer/>;break;case'match':body=<Match go={setScreen}/>;break;case'skills':body=<Skills/>;break;case'shooting':body=<Shooting/>;break;case'goalkeeper':body=<Goalkeeper/>;break;case'team':body=<Team/>;break;case'coach':body=<Coach/>;break;case'progress':body=<Progression/>;break;case'settings':body=<Settings/>}return <div className={`app screen-${screen}`}>{!['match','goalkeeper'].includes(screen)&&<TopBar screen={screen} setScreen={setScreen}/>}<main>{body}</main></div>}
